# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170617_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/'),
        ),
    ]
